""" revisão de tipagem na coluna 'saldo' da tabela Contas implementando o metodod Mapped

Revision ID: 5a10cf8dc10f
Revises: 2571fb117954
Create Date: 2026-04-07 18:40:22.476640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a10cf8dc10f'
down_revision: Union[str, Sequence[str], None] = '2571fb117954'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contas', schema=None) as batch_op:
        batch_op.alter_column('saldo',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contas', schema=None) as batch_op:
        batch_op.alter_column('saldo',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###
